/*
 * test-proxy-protocol-e2e.cpp — Story 2.10 AC #1 #2 #3 #5.
 *
 * E2E driver for PROXY-protocol v1/v2 client-IP propagation through the
 * CF Worker → nginx → teleproxy server chain.  In CI the "CF Worker" and
 * "nginx" are replaced by a minimal C++ framing shim that injects the
 * PROXY-protocol header directly onto the upstream TCP connection.
 *
 * Compile (Linux, standalone — no Qt required for the shim driver):
 *   g++ -std=c++17 -O2 -o test-proxy-protocol-e2e \
 *       test-proxy-protocol-e2e.cpp -lpthread
 *
 * Usage:
 *   ./test-proxy-protocol-e2e --version v1 [--no-cdn] [--server-port 13129]
 *                              [--stats-port 8889]
 *                              [--binary PATH/TO/mtproto-proxy]
 *                              [--aes-pwd PATH] [--secret HEX]
 *
 * Exit codes:
 *   0  all assertions passed
 *   1  assertion failure (details on stderr)
 *   2  server launch or connectivity failure
 *
 * Story 2.10 §Sandbox-vs-prod caveat: this driver uses sandbox credentials
 * generated by gen-sandbox-secrets.sh.  Never pass production credentials.
 */

#include <cassert>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <algorithm>

#include <unistd.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <arpa/inet.h>

/* ── Constants ─────────────────────────────────────────────────────────── */

/* RFC 5737 TEST-NET-3 — safe for CI fixtures (never routes to real hosts). */
static const char *kTestClientIP   = "198.51.100.42";
static const int   kTestClientPort = 12345;

/* ── Helpers ────────────────────────────────────────────────────────────── */

static void die(const char *msg) {
    perror(msg);
    exit(2);
}

static void fail(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    fprintf(stderr, "[FAIL] ");
    vfprintf(stderr, fmt, ap);
    fprintf(stderr, "\n");
    va_end(ap);
    exit(1);
}

static void info(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    fprintf(stderr, "[INFO] ");
    vfprintf(stderr, fmt, ap);
    fprintf(stderr, "\n");
    va_end(ap);
}

/* ── PROXY-protocol framing shim ────────────────────────────────────────── */

/* Build a PROXY-protocol v1 (text) header for TCP4.
 * Format: "PROXY TCP4 <src> <dst> <sport> <dport>\r\n"  */
static std::string build_pp_v1(const char *src_ip, int src_port,
                                const char *dst_ip, int dst_port) {
    char buf[128];
    snprintf(buf, sizeof(buf), "PROXY TCP4 %s %s %d %d\r\n",
             src_ip, dst_ip, src_port, dst_port);
    return std::string(buf);
}

/* Build a PROXY-protocol v2 (binary) header for TCP4.
 * Signature: 12-byte magic + 4-byte header + 12-byte address block.  */
static std::vector<uint8_t> build_pp_v2(const char *src_ip, int src_port,
                                         const char *dst_ip, int dst_port) {
    static const uint8_t kMagic[12] = {
        0x0d,0x0a,0x0d,0x0a, 0x00,0x0d,0x0a,0x51, 0x55,0x49,0x54,0x0a
    };
    std::vector<uint8_t> hdr;
    hdr.insert(hdr.end(), kMagic, kMagic + 12);
    /* version=2, command=PROXY(1) */
    hdr.push_back(0x21);
    /* family=AF_INET(1), protocol=TCP(1) → 0x11 */
    hdr.push_back(0x11);
    /* length of address block: 4+4+2+2 = 12 bytes */
    hdr.push_back(0x00);
    hdr.push_back(0x0c);

    /* src IPv4 */
    struct in_addr src_addr, dst_addr;
    inet_aton(src_ip, &src_addr);
    inet_aton(dst_ip, &dst_addr);
    uint32_t s = src_addr.s_addr, d = dst_addr.s_addr;
    hdr.push_back((s      ) & 0xff); hdr.push_back((s >>  8) & 0xff);
    hdr.push_back((s >> 16) & 0xff); hdr.push_back((s >> 24) & 0xff);
    /* dst IPv4 */
    hdr.push_back((d      ) & 0xff); hdr.push_back((d >>  8) & 0xff);
    hdr.push_back((d >> 16) & 0xff); hdr.push_back((d >> 24) & 0xff);
    /* src port (big-endian) */
    hdr.push_back((src_port >> 8) & 0xff);
    hdr.push_back((src_port     ) & 0xff);
    /* dst port (big-endian) */
    hdr.push_back((dst_port >> 8) & 0xff);
    hdr.push_back((dst_port     ) & 0xff);
    return hdr;
}

/* ── Server subprocess management ──────────────────────────────────────── */

struct ServerProc {
    pid_t   pid     = -1;
    int     log_fd  = -1;   /* read end of pipe for stderr */
};

static ServerProc launch_server(const char *binary,
                                const char *aes_pwd,
                                const char *secret_hex,
                                int server_port,
                                int stats_port,
                                bool proxy_protocol_enabled) {
    int pipe_fds[2];
    if (pipe(pipe_fds) < 0) die("pipe");

    pid_t pid = fork();
    if (pid < 0) die("fork");

    if (pid == 0) {
        /* Child: redirect stderr to pipe write end. */
        dup2(pipe_fds[1], STDERR_FILENO);
        close(pipe_fds[0]);
        close(pipe_fds[1]);

        char port_str[16], stats_str[16];
        snprintf(port_str,  sizeof(port_str),  "%d", server_port);
        snprintf(stats_str, sizeof(stats_str), "%d", stats_port);

        std::vector<const char *> argv;
        argv.push_back(binary);
        argv.push_back("-p"); argv.push_back(port_str);
        argv.push_back("--aes-pwd"); argv.push_back(aes_pwd);
        argv.push_back("-S"); argv.push_back(secret_hex);
        argv.push_back("-M"); argv.push_back("1");
        argv.push_back("--stats-port"); argv.push_back(stats_str);
        if (proxy_protocol_enabled) {
            argv.push_back("--proxy-protocol");
        }
        argv.push_back(nullptr);

        execv(binary, const_cast<char *const *>(argv.data()));
        perror("execv");
        _exit(2);
    }

    /* Parent: close write end; child holds it via dup2 until exit. */
    close(pipe_fds[1]);

    ServerProc sp;
    sp.pid    = pid;
    sp.log_fd = pipe_fds[0];
    return sp;
}

static void stop_server(ServerProc &sp) {
    if (sp.pid > 0) {
        kill(sp.pid, SIGTERM);
        int status;
        waitpid(sp.pid, &status, 0);
        sp.pid = -1;
    }
    if (sp.log_fd >= 0) { close(sp.log_fd); sp.log_fd = -1; }
}

static std::string drain_log(int fd) {
    std::string out;
    char buf[4096];
    /* Set non-blocking so we don't hang if the buffer is already empty. */
    int flags = fcntl(fd, F_GETFL, 0);
    fcntl(fd, F_SETFL, flags | O_NONBLOCK);
    ssize_t n;
    while ((n = read(fd, buf, sizeof(buf))) > 0) {
        out.append(buf, (size_t)n);
    }
    fcntl(fd, F_SETFL, flags);
    return out;
}

/* ── Metrics scraping ──────────────────────────────────────────────────── */

static std::string scrape_metrics(const char *host, int port) {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) return "";

    struct sockaddr_in addr = {};
    addr.sin_family      = AF_INET;
    addr.sin_port        = htons((uint16_t)port);
    addr.sin_addr.s_addr = inet_addr(host);

    if (connect(fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(fd);
        return "";
    }

    const char *req = "GET /metrics HTTP/1.0\r\nHost: 127.0.0.1\r\n\r\n";
    if (write(fd, req, strlen(req)) < 0) { close(fd); return ""; }

    std::string body;
    char buf[4096];
    ssize_t n;
    while ((n = read(fd, buf, sizeof(buf))) > 0) body.append(buf, (size_t)n);
    close(fd);
    return body;
}

/* Find the (integer) value of a Prometheus counter line "name value\n". */
static long long find_counter(const std::string &body, const char *name) {
    std::string search = std::string(name) + " ";
    auto pos = body.find(search);
    if (pos == std::string::npos) return -1;
    return std::atoll(body.c_str() + pos + search.size());
}

/* ── Connection shim: inject PP header then forward raw bytes ───────────── */

static int connect_to(const char *host, int port) {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) return -1;
    struct sockaddr_in addr = {};
    addr.sin_family      = AF_INET;
    addr.sin_port        = htons((uint16_t)port);
    addr.sin_addr.s_addr = inet_addr(host);
    if (connect(fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(fd);
        return -1;
    }
    return fd;
}

static bool send_all(int fd, const void *buf, size_t len) {
    const uint8_t *p = (const uint8_t *)buf;
    while (len > 0) {
        ssize_t n = write(fd, p, len);
        if (n <= 0) return false;
        p   += (size_t)n;
        len -= (size_t)n;
    }
    return true;
}

/* Send a PP header then close (simulates a minimal "client knock"). */
static bool inject_and_knock(int server_port,
                              const std::string &pp_header_v1,
                              const std::vector<uint8_t> &pp_header_v2,
                              bool use_v1) {
    int fd = connect_to("127.0.0.1", server_port);
    if (fd < 0) return false;

    bool ok;
    if (use_v1) {
        ok = send_all(fd, pp_header_v1.data(), pp_header_v1.size());
    } else {
        ok = send_all(fd, pp_header_v2.data(), pp_header_v2.size());
    }

    usleep(50000);  /* 50 ms */
    close(fd);
    return ok;
}

/* Bare TCP connect + close (no PP header — for no-cdn AC#3 path). */
static bool bare_knock(int server_port) {
    int fd = connect_to("127.0.0.1", server_port);
    if (fd < 0) return false;
    usleep(50000);
    close(fd);
    return true;
}

/* ── Wait helpers ───────────────────────────────────────────────────────── */

static bool wait_for_port(const char *host, int port, int timeout_ms) {
    int elapsed = 0;
    while (elapsed < timeout_ms) {
        int fd = connect_to(host, port);
        if (fd >= 0) { close(fd); return true; }
        usleep(50000);
        elapsed += 50;
    }
    return false;
}

/* ── Test cases ─────────────────────────────────────────────────────────── */

struct Config {
    const char *binary      = "./teleproto3/server/objs/bin/mtproto-proxy";
    const char *aes_pwd     = "tdesktop/tests/fixtures/sandbox-secret";
    const char *secret_hex  = nullptr;  /* read from sandbox-type3-secret.hex */
    int  server_port        = 13129;
    int  stats_port         = 8889;
    bool use_v1             = true;     /* false → v2 */
    bool no_cdn             = false;
};

static std::string read_file(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return "";
    char buf[256];
    fgets(buf, sizeof(buf), f);
    fclose(f);
    /* strip trailing newline */
    size_t n = strlen(buf);
    while (n > 0 && (buf[n-1] == '\n' || buf[n-1] == '\r')) buf[--n] = '\0';
    return std::string(buf);
}

static int run_tests(const Config &cfg) {
    std::string secret_hex = cfg.secret_hex
        ? std::string(cfg.secret_hex)
        : read_file("tdesktop/tests/fixtures/sandbox-type3-secret.hex");

    if (secret_hex.empty()) {
        fprintf(stderr, "ERROR: sandbox-type3-secret.hex not found. "
                "Run gen-sandbox-secrets.sh first.\n");
        return 2;
    }

    /* ── Launch server ── */
    info("Launching server on port %d (proxy-protocol=%s, pp-version=%s)",
         cfg.server_port,
         cfg.no_cdn ? "disabled" : "enabled",
         cfg.use_v1 ? "v1" : "v2");

    ServerProc srv = launch_server(
        cfg.binary, cfg.aes_pwd, secret_hex.c_str(),
        cfg.server_port, cfg.stats_port, !cfg.no_cdn);

    /* Wait up to 3 s for server + stats port to be ready. */
    if (!wait_for_port("127.0.0.1", cfg.server_port, 3000)) {
        stop_server(srv);
        fprintf(stderr, "ERROR: server did not accept connections on port %d\n",
                cfg.server_port);
        return 2;
    }
    if (!wait_for_port("127.0.0.1", cfg.stats_port, 3000)) {
        stop_server(srv);
        fprintf(stderr, "ERROR: stats endpoint not ready on port %d\n",
                cfg.stats_port);
        return 2;
    }

    /* ── Scrape baseline metrics ── */
    std::string baseline = scrape_metrics("127.0.0.1", cfg.stats_port);
    long long pp_conns_before = find_counter(baseline, "proxy_protocol_connections_total");
    long long pp_errs_before  = find_counter(baseline, "proxy_protocol_errors_total");
    long long t3_conns_before = find_counter(baseline,
        "teleproto3_connections_total{command_type=\"type3\"}");

    info("Baseline: pp_connections=%lld, pp_errors=%lld, t3_type3=%lld",
         pp_conns_before, pp_errs_before, t3_conns_before);

    /* ── Inject knock ── */
    if (cfg.no_cdn) {
        /* AC #3 — bare TCP connection, no PP header. */
        if (!bare_knock(cfg.server_port)) {
            stop_server(srv);
            fail("Failed to connect to server (bare knock, no-cdn)");
        }
    } else {
        /* AC #1 — inject PP v1 or v2 header. */
        std::string pp_v1 = build_pp_v1(kTestClientIP, kTestClientPort,
                                         "127.0.0.1", cfg.server_port);
        std::vector<uint8_t> pp_v2 = build_pp_v2(kTestClientIP, kTestClientPort,
                                                   "127.0.0.1", cfg.server_port);
        if (!inject_and_knock(cfg.server_port, pp_v1, pp_v2, cfg.use_v1)) {
            stop_server(srv);
            fail("Failed to send PROXY-protocol header to server");
        }
    }

    /* Allow server to process the connection. */
    usleep(500000);  /* 500 ms — generous for loaded CI runners */

    /* ── Scrape post-knock metrics ── */
    std::string after = scrape_metrics("127.0.0.1", cfg.stats_port);
    long long pp_conns_after = find_counter(after, "proxy_protocol_connections_total");
    long long pp_errs_after  = find_counter(after, "proxy_protocol_errors_total");

    info("After knock: pp_connections=%lld, pp_errors=%lld",
         pp_conns_after, pp_errs_after);

    /* ── AC #1 / AC #3: assert counter behaviour ── */
    if (cfg.no_cdn) {
        /* AC #3 — no PP header sent: pp_connections must NOT increment. */
        if (pp_conns_after != pp_conns_before) {
            stop_server(srv);
            fail("AC#3: proxy_protocol_connections_total should not increment "
                 "when --proxy-protocol is disabled. Before=%lld After=%lld",
                 pp_conns_before, pp_conns_after);
        }
        info("AC#3 PASS: proxy_protocol_connections_total unchanged (%lld)", pp_conns_after);
    } else {
        /* AC #1 — PP header: pp_connections MUST increment, no new errors. */
        if (pp_conns_after <= pp_conns_before) {
            stop_server(srv);
            fail("AC#1: proxy_protocol_connections_total did not increment. "
                 "Before=%lld After=%lld", pp_conns_before, pp_conns_after);
        }
        if (pp_errs_after > pp_errs_before) {
            stop_server(srv);
            fail("AC#1: proxy_protocol_errors_total increased. "
                 "Before=%lld After=%lld", pp_errs_before, pp_errs_after);
        }
        info("AC#1 PASS: proxy_protocol_connections_total incremented to %lld, "
             "errors unchanged (before=%lld after=%lld)",
             pp_conns_after, pp_errs_before, pp_errs_after);
    }

    /* ── AC #1 tripwire: per-IP counters (upstream be46337/f083b07) ── */
    if (!cfg.no_cdn) {
        if (after.find("per_ip_top_n") != std::string::npos ||
            after.find("rate_limit_bucket") != std::string::npos) {
            stop_server(srv);
            fail("TRIPWIRE: per-IP counters detected in /metrics but AC#1 "
                 "per-IP assertions are not implemented. Update this test to "
                 "verify parsed IP feeds per-IP rate-limit and top-N counters.");
        }
    }

    /* ── AC #2: NFR19 — client IP must not appear in default-verbosity log ── */
    usleep(100000);  /* 100 ms — let server flush stderr */
    std::string log_buf = drain_log(srv.log_fd);
    if (log_buf.find(kTestClientIP) != std::string::npos) {
        stop_server(srv);
        fail("AC#2 NFR19 VIOLATION: client IP '%s' found in server log at "
             "default verbosity:\n%s", kTestClientIP, log_buf.c_str());
    }
    info("AC#2 PASS: NFR19 — client IP '%s' not present in default-verbosity log",
         kTestClientIP);

    stop_server(srv);
    info("All assertions PASSED (%s, %s)",
         cfg.no_cdn ? "no-cdn" : (cfg.use_v1 ? "pp-v1" : "pp-v2"),
         "default verbosity");
    return 0;
}

/* ── main ────────────────────────────────────────────────────────────────── */

static void usage(const char *prog) {
    fprintf(stderr,
        "Usage: %s --version {v1|v2} [--no-cdn]\n"
        "          [--server-port PORT] [--stats-port PORT]\n"
        "          [--binary PATH] [--aes-pwd PATH] [--secret HEX]\n",
        prog);
}

int main(int argc, char *argv[]) {
    Config cfg;

    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--version" && i + 1 < argc) {
            ++i;
            cfg.use_v1 = (std::string(argv[i]) == "v1");
        } else if (a == "--no-cdn") {
            cfg.no_cdn = true;
        } else if (a == "--server-port" && i + 1 < argc) {
            cfg.server_port = std::atoi(argv[++i]);
        } else if (a == "--stats-port" && i + 1 < argc) {
            cfg.stats_port = std::atoi(argv[++i]);
        } else if (a == "--binary" && i + 1 < argc) {
            cfg.binary = argv[++i];
        } else if (a == "--aes-pwd" && i + 1 < argc) {
            cfg.aes_pwd = argv[++i];
        } else if (a == "--secret" && i + 1 < argc) {
            cfg.secret_hex = argv[++i];
        } else {
            usage(argv[0]);
            return 2;
        }
    }

    return run_tests(cfg);
}
