/*
This file is part of Telegram Desktop,
the official desktop application for the Telegram messaging service.

For license and copyright information please follow this link:
https://github.com/telegramdesktop/tdesktop/blob/master/LEGAL
*/
#pragma once

#include "lang_auto.h"
#include "lang/lang_hardcoded.h"
#include "lang/lang_text_entity.h"

#include <QDateTime>

[[nodiscard]] QString langDayOfMonth(const QDate &date);
[[nodiscard]] QString langDayOfMonthFull(const QDate &date);
[[nodiscard]] QString langDayOfMonthShort(const QDate &date);
[[nodiscard]] QString langMonthOfYear(int month, int year);
[[nodiscard]] QString langMonth(const QDate &date);
[[nodiscard]] QString langMonthOfYearFull(int month, int year);
[[nodiscard]] QString langMonthFull(const QDate &date);
[[nodiscard]] QString langDayOfWeek(int index);
[[nodiscard]] QString langDayOfWeekFull(int index);

[[nodiscard]] inline QString langDayOfWeek(const QDate &date) {
	return langDayOfWeek(date.dayOfWeek());
}

[[nodiscard]] inline QString langDayOfWeekFull(const QDate &date) {
	return langDayOfWeekFull(date.dayOfWeek());
}

[[nodiscard]] QString langDateTime(const QDateTime &date);
[[nodiscard]] QString langDateTimeFull(const QDateTime &date);
[[nodiscard]] bool langFirstNameGoesSecond();

namespace Lang {

[[nodiscard]] QString Id();
[[nodiscard]] rpl::producer<> Updated();
[[nodiscard]] QString GetNonDefaultValue(const QByteArray &key);
[[nodiscard]] QString DefaultLanguageId();
[[nodiscard]] QString LanguageIdOrDefault(const QString &id);

[[nodiscard]] tr::phrase<> Month(int index);
[[nodiscard]] tr::phrase<> MonthSmall(int index);
[[nodiscard]] tr::phrase<> MonthDay(int index);
[[nodiscard]] tr::phrase<> Weekday(int index);
[[nodiscard]] tr::phrase<> WeekdayFull(int index);

} // namespace Lang

/* === TYPE3-PROXY BEGIN === */
// <type3-strings:begin> // codegen target — see tdesktop/build/codegen-t3-strings.{py,cmake}
// Generated by codegen-t3-strings.py from teleproto3/spec/ux-strings.yaml.
// DO NOT edit this section manually — edit ux-strings.yaml and re-run codegen.
// Append-only: story 2.6 owns this section; host-app strings above are out of scope.
//
// Ban-list: none of the string values below contain the seven banned tokens
// (proxy / прокси / پروکسی / 代理 / proxy-server / bypass / censorship).
namespace t3lang {

// ui.tier3-toast (AC#3) — non-modal toast body on tier-3 halt.
[[nodiscard]] inline QString lng_t3_tier3_toast() {
    // TODO(codegen): replace with locale-aware lookup; en value is authoritative.
    return u"Connection unstable. Tap to choose a different server or use direct connection."_q;
}

// ui.tier3-action-switch (AC#3) — single tappable action label on tier-3 toast.
[[nodiscard]] inline QString lng_t3_tier3_action_switch() {
    // TODO(codegen): replace with locale-aware lookup; en value is authoritative.
    return u"Choose"_q;
}

// ui.secure-storage-unavailable (story 2.4 PREREQUISITE via story 2.6) — startup warning.
[[nodiscard]] inline QString lng_t3_secure_storage_unavailable() {
    // TODO(codegen): replace with locale-aware lookup; en value is authoritative.
    return u"Secure storage unavailable"_q;
}

// ui.update-failed-generic (story 2.7 AC#4 / NFR20) — Linux AppImage update
// failure surface. MUST NOT differentiate failure class (NFR20). Ban-list
// clean. The string MUST NOT mention "signature", "key", "verification",
// "tampered", or any token that lets a network adversary distinguish an
// integrity attack from a transient network failure.
[[nodiscard]] inline QString lng_update_failed_generic() {
    // TODO(codegen): replace with locale-aware lookup; en value is authoritative.
    return u"Update could not be applied. The current version will continue "
           "to work. Please try again later or download the update manually "
           "from the official site."_q;
}

// ui.group-calls-unsupported (story 9-1 AC#5) — shown when Mtproto3 proxy is active and user taps group call.
// Per AC#5: RU+EN, no jargon, no banned tokens.
[[nodiscard]] inline QString lng_t3_group_calls_unsupported() {
    // TODO(codegen): replace with locale-aware lookup; en value is authoritative.
    return u"Групповые звонки в этой версии не поддерживаются — используйте обычный Telegram для групп. "
           "(Group calls not supported in this version — use stock Telegram for groups.)"_q;
}

} // namespace t3lang
// <type3-strings:end>
/* === TYPE3-PROXY END === */
