# Story 2-9: Generate t3_default_proxy.gen.h from .credentials
# This script is invoked by CMake at configure time.
# If .credentials exists, parses it and emits #defines.
# If not, emits empty defaults so the build still succeeds.

get_filename_component(CREDENTIALS_FILE "${CMAKE_SOURCE_DIR}/../../.credentials" REALPATH)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/gen")
set(OUTPUT_HEADER "${CMAKE_CURRENT_BINARY_DIR}/gen/t3_default_proxy.gen.h")

set(T3_DEFAULT_SERVER "")
set(T3_DEFAULT_PORT "0")
set(T3_DEFAULT_SECRET "")

if(EXISTS "${CREDENTIALS_FILE}")
    file(STRINGS "${CREDENTIALS_FILE}" _cred_lines)
    foreach(_line ${_cred_lines})
        # Skip comments and empty lines
        string(REGEX MATCH "^#" _is_comment "${_line}")
        if(_is_comment)
            continue()
        endif()

        # WS_DOMAIN=... (v2 direct) or WORKER_DOMAIN=... (legacy CF Workers)
        string(REGEX MATCH "^WS_DOMAIN=(.+)$" _match "${_line}")
        if(_match)
            set(T3_DEFAULT_SERVER "${CMAKE_MATCH_1}")
        endif()
        string(REGEX MATCH "^WORKER_DOMAIN=(.+)$" _match "${_line}")
        if(_match AND "${T3_DEFAULT_SERVER}" STREQUAL "")
            set(T3_DEFAULT_SERVER "${CMAKE_MATCH_1}")
        endif()

        # TYPE3_SECRET=...
        string(REGEX MATCH "^TYPE3_SECRET=(.+)$" _match "${_line}")
        if(_match)
            set(T3_DEFAULT_SECRET "${CMAKE_MATCH_1}")
        endif()
    endforeach()

    # Port is always 443 for WS/TLS
    if(NOT "${T3_DEFAULT_SERVER}" STREQUAL "")
        set(T3_DEFAULT_PORT "443")
    endif()

    message(STATUS "[T3] Default proxy from .credentials: ${T3_DEFAULT_SERVER}:${T3_DEFAULT_PORT}")
else()
    message(STATUS "[T3] No .credentials found — building without default proxy")
endif()

file(WRITE "${OUTPUT_HEADER}"
    "// Auto-generated by generate_default_proxy.cmake — DO NOT COMMIT\n"
    "// Source: .credentials (gitignored)\n"
    "#pragma once\n"
    "\n"
    "#define T3_DEFAULT_SERVER \"${T3_DEFAULT_SERVER}\"\n"
    "#define T3_DEFAULT_PORT ${T3_DEFAULT_PORT}\n"
    "#define T3_DEFAULT_SECRET \"${T3_DEFAULT_SECRET}\"\n"
)
